name: Build

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install cross-compiler
      run: |
        sudo apt update
        sudo apt install gcc-aarch64-linux-gnu
        mkdir -p .cargo
        echo [target.aarch64-unknown-linux-gnu] > .cargo/config.toml
        echo linker = '"'aarch64-linux-gnu-gcc'"' >> .cargo/config.toml

    - name: Install cross-compiling toolchain
      if: matrix.cross
      run: rustup target add aarch64-unknown-linux-gnu
      
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --target aarch64-unknown-linux-gnu
      env:
        CC: aarch64-linux-gnu-gcc
